fish_dict = {
    "Blue Whale": [1, '', ''],
    "Humpback Whale": [2, '', ''],
    "Whale Shark": [3, '', ''],
    "Great White Shark": [3, '', ''],
    "Swordfish": [5, '', ''],
    "Marlin": [5, '', ''],
    "Barracuda": [5, '', ''],
    "Giant Squid": [5, '', ''],
    "Bottlenose Dolphin": [8, '', ''],
    "Dolphin": [8, '', ''],
    "Tuna": [12, '', ''],
    "Barramundi": [12, '', ''],
    "Angelfish": [12, '', ''],
    "Sea Dragon": [20, '', ''],
    "Electric Eel": [20, '', ''],
    "Blobfish": [20, '', ''],
    "Lionfish": [20, '', ''],
    "Pufferfish": [20, '', ''],
    "Stingray": [25, '', ''],
    "Moray Eel": [35, '', ''],
    "Giant Clam": [35, '', ''],
    "Stonefish": [40, '', ''],
    "Lobster": [40, '', ''],
    "Mantis Shrimp": [45, '', ''],
    "Boxfish": [50, '', ''],
    "Squid": [60, '', ''],
    "Salmon": [80, '', ''],
    "Octopus": [80, '', ''],
    "Piranha": [100, '', ''],
    "Seahorse": [100, '', ''],
    "Cuttlefish": [120, '', ''],
    "Sea Urchin": [125, '', ''],
    "Hermit Crab": [150, '', ''],
    "Blue Tang": [175, '', ''],
    "Clownfish": [200, '', ''],
    "Neon Tetra": [200, '', ''],
    "Minnow": [200, '', ''],
    "Sardine": [250, '', ''],
    "Sea Cucumber": [275, '', ''],
    "Clam": [275, '', ''],
    "Jellyfish": [400, '', ''],
    "Sea Bass": [400, '', ''],
    "Mackerel": [400, '', ''],
    "Goldfish": [450, '', ''],
    "Trout": [500, '', ''],
    "Guppy": [500, '', ''],
    "Anchovy": [500, '', ''],
}